### ISSUE TITLE
Personal access token does not work, requires `Authorization: TOKEN` header, not `Authorization: Bearer TOKEN`

### ISSUE THREAD

**Issue by igoradaptyv** [turbot/steampipe-plugin-linear#27]
**Describe the bug**
I followed the guide on https://hub.steampipe.io/plugins/turbot/linear to set up the plugin and created a personal access token at https://linear.app/$MYORG/settings/api . As noted in the https://hub.steampipe.io/plugins/turbot/linear documentation 

```
  # `token` - API token for your Linear account. It can be a personal access key or OAuth2 token. Required.
```

On executing 

```
select
  id,
  title,
  created_at,
  branch_name,
  priority,
  estimate,
  updated_at
from
  linear_issue
where
  assignee is null;
  ```
  
it throws the error

```
Error: linear: returned error 400 Bad Request: {"errors":[{"message":"Context creation failed: It looks like you're trying to use an API key as a Bearer token. Remove the Bearer prefix from the Authorization header.","extensions":{"code":"INPUT_ERROR","type":"invalid input","userError":true,"meta":{}}}]}
 (SQLSTATE HV000)
 ```
 
 
**Steampipe version (`steampipe -v`)**
Steampipe v0.21.7

**Plugin version (`steampipe plugin list`)**
 `| hub.steampipe.io/plugins/turbot/linear@latest  | 0.2.0   | linear      |`

**To reproduce**
See description

**Expected behavior**

The query to complete, at least on issues I have access to.
Alternatively, for the documentation to note you need a workspace wide acess token

**Additional context**

Fix would be to change this line https://github.com/turbot/steampipe-plugin-linear/blob/45c1f2c00495ce4c91a5562f1159950e4a31cb94/linear/utils.go#L24 to check whether we have an OAUTH2 or a personal token and dispatch accordingly to set `Authorzation: TOKEN` instead of `Authorization: Bearer  TOKEN` as noted in https://developers.linear.app/docs/graphql/working-with-the-graphql-api

**Comment by ChristianWitts** [comment]
@misraved @bigdatasourav while the code has been fixed, the fix has not been released.

I had to build from source so that the plugin was actually usable with an API key.

**Comment by misraved** [comment]
Apologies for missing out on the release of the fix @ChristianWitts !!

I will push out a release along with this [PR](https://github.com/turbot/steampipe-plugin-linear/pull/34) shortly 👍.

Thanks for pointing it out!

**Comment by ChristianWitts** [comment]
Thanks so much @misraved 🙏
